#pragma once

#define FS_MAGIC_NUMBER 0x46530001U
#define FS_MAX_FILENAME_LENGTH 255U
#define FS_CLUSTER_SIZE 4096U
#define FS_INODE_COUNT 1024U
#define FS_DIRECT_POINTERS 12U

#define FS_SUPERBLOCK_CLUSTER_INDEX 0U
#define FS_BITMAP_START_CLUSTER_INDEX 1U

#define FS_BITMAP_INODE_ID 0U
#define FS_INDEX_TABLE_INODE_ID 1U
#define FS_ROOT_INODE_ID 2U